version: '3'

services:
  install:
    container_name: composer
    image: composer
    user: 1000:1000
    command: sh -c 'composer create-project --prefer-dist laravel/laravel laravel && chmod -R o+w laravel/storage/framework && chmod -R o+w laravel/storage/logs && sed -i "s/\(DB_CONNECTION=\).*/\1pgsql/" laravel/.env && sed -i "s/\(DB_HOST=\).*/\1postgres/" laravel/.env && sed -i "s/\(DB_PORT=\).*/\15432/" laravel/.env && sed -i "s/\(DB_DATABASE=\).*/\1laravel/" laravel/.env && sed -i "s/\(DB_USERNAME=\).*/\1root/" laravel/.env && sed -i "s/\(DB_PASSWORD=\).*/\1root/" laravel/.env'
    working_dir: /app
    volumes:
      - ./:/app

  php:
    container_name: php
    build: php
    working_dir: /usr/share/nginx/html
    ports:
      - 9000:9000
    volumes:
      - ./laravel:/usr/share/nginx/html

  nginx:
    container_name: nginx
    depends_on:
      - php
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./laravel:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
  
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: laravel

  
  adminer:
    container_name: adminer
    depends_on:
      - postgres
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080